; PlatformIO Project Configuration File

[platformio]
name = garage-doors
description = Garage Doors (4-channel relay controller)
default_envs = debug

[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

board_build.partitions = zigbee.csv

lib_extra_dirs = ../libraries
lib_deps =
    Preferences

monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
monitor_filters =
    time

[env:release]
extends = base
build_flags =
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=0
    -Os

[env:debug]
extends = base
build_flags =
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDEBUG
