[platformio]
description  = Garage Water
default_envs = debug

[base]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino

board_build.partitions = zigbee.csv
board_build.filesystem = spiffs

monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF

[env:release]
extends = base
build_flags = 
    -DZIGBEE_MODE_ED

[env:debug]
extends = env:release
build_flags = 
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    #-DCONFIG_TINYUSB_CDC_ENABLED=1
    #-DCORE_DEBUG_LEVEL=1
    -DDEBUG
